language: c
sudo: false
env:
  global:
    - RACKET_DIR=~/racket
  matrix:
    - RACKET_VERSION="7.6"
    - RACKET_VERSION="7.7"
    - RACKET_VERSION="7.8"
    - RACKET_VERSION="7.9"
    - RACKET_VERSION="HEAD"
matrix:
  allow_failures:
    - env: RACKET_VERSION="HEAD"

before_install:
  - git clone https://github.com/greghendershott/travis-racket.git ../travis-racket
  - cat ../travis-racket/install-racket.sh | bash
  - export PATH="${RACKET_DIR}/bin:${PATH}"
  # install Turnstile, use `master` branch
  # - git clone https://github.com/stchang/macrotypes.git
  # - raco pkg install --auto macrotypes/macrotypes-lib/
  # - raco pkg install --auto macrotypes/turnstile-lib/
  # - raco pkg install --auto macrotypes/rackunit-macrotypes-lib/
  - raco pkg install --skip-installed --batch --auto https://github.com/cpsc411/cpsc411-pub.git?path=cpsc411-lib

install:
 - raco pkg install --skip-installed --batch --auto https://github.com/cpsc411/compilers2.0.git?path=cpsc411-priv/cpsc411-reference-lib

script:
 - raco test --package cpsc411-interrogator-lib
 - raco setup
