# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run.
on: [push, pull_request]
#
#  # Allows you to run this workflow manually from the Actions tab
#  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build-and-test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        racket-version: ['7.4', '7.5', '7.6', '7.7', '7.8', '7.9', '8.0', '8.1', '8.2', '8.3', 'current']
        racket-variant: ['CS', 'BC']
#        nasm: [2.13,2.14,2.15]
    steps:
    - name: Install system dependencies
      run: |
        sudo apt-get install nasm
    - name: Install Racket
      uses: Bogdanp/setup-racket@v1.7
      with:
        architecture: 'x64'
        distribution: 'full'
        variant: ${{ matrix.racket-variant }}
        version: ${{ matrix.racket-version }}
    - name: Checkout private dependencies
      uses: actions/checkout@v2
      with:
        repository: cpsc411/cpsc411-priv
        ref: 2021w2
        ssh-key: ${{ secrets.PRIV_SSH_KEY }}
        path: cpsc411-priv
    - name: Checkout
      uses: actions/checkout@v2
      with:
        path: cpsc411-interrogator
    - name: Install dependencies
      run: |
        raco pkg install --batch --auto \
          https://github.com/cpsc411/cpsc411-pub.git?path=cpsc411-lib#2021w2 \
          ./cpsc411-priv/cpsc411-reference-tests \
          ./cpsc411-priv/cpsc411-reference-lib \
    - name: Workaround base version requirement
      run: |
        sed -i 's/ #:version \"8.2\"//' ./cpsc411-interrogator/cpsc411-interrogator-lib/info.rkt
    - name: Build lib
      run: |
        raco pkg install --batch --auto ./cpsc411-interrogator/cpsc411-interrogator-lib
    - name: Test lib
      run: |
        raco test -p cpsc411-interrogator-lib
    - name: Test lib setup
      run: |
        raco setup --only --pkgs cpsc411-interrogator-lib
