# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. 
on: [push, pull_request]
#
#  # Allows you to run this workflow manually from the Actions tab
#  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build-and-test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        racket: [7.4,7.5,7.6,7.7,7.8,7.9,current]
#        nasm: [2.13,2.14,2.15]
    steps:
    - name: Install system dependencies
      run: |
        sudo apt-get install nasm
    - name: Install Racket
      uses: Bogdanp/setup-racket@v0.12
      with:
        architecture: 'x64'
        distribution: 'full' #'minimal'
        version: ${{ matrix.racket }}
    - name: Install pub dependencies
      run: sudo raco pkg install --batch --auto https://github.com/cpsc411/cpsc411-pub.git?path=cpsc411-lib#2020w2
    - name: Checkout private dependencies
      uses: actions/checkout@v2
      with:
        repository: cpsc411/compilers2.0
        ref: main
        ssh-key: ${{ secrets.PRIV_SSH_KEY }}
        path: compilers2.0
    - name: Install private dependencies
      run: |
        pushd compilers2.0/cpsc411-priv/cpsc411-reference-tests
        sudo raco pkg install --batch --auto
        popd
        pushd compilers2.0/cpsc411-priv/cpsc411-reference-lib
        sudo raco pkg install --batch --auto
    - name: Checkout
      uses: actions/checkout@v2
    - name: Build lib
      run: |
        sudo raco pkg install --batch --auto ./cpsc411-interrogator-lib
    - name: Test lib
      run: |
        raco test -p cpsc411-interrogator-lib
        sudo raco setup --only --pkgs cpsc411-interrogator-lib
