# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. 
on: [push, pull_request]
#
#  # Allows you to run this workflow manually from the Actions tab
#  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build-and-test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        racket: [7.4,7.5,7.6,7.7,7.8,7.9,current]
#        nasm: [2.13,2.14,2.15]
    steps:
    - name: Install system dependencies
      run: |
        sudo apt-get install nasm
    - name: Install Racket
      uses: Bogdanp/setup-racket@v0.12
      with:
        architecture: 'x64'
        distribution: 'full' #'minimal'
        version: ${{ matrix.racket }}
    - name: Setup SSH
      env:
        SSH_AUTH_SOCK: /tmp/ssh_agent.sock
      run: |
        mkdir -p ~/.ssh
        ssh-keyscan github,com >> ~/.ssh/known_hosts
        ssh-agent -a $SSH_AUTH_SOCK > /dev/null
        ssh-add - <<< "${{ secrets.PRIV_SSH_KEY }}"
    - name: Install dependencies
      run: |
        raco pkg install --batch --auto |
          https://github.com/cpsc411/cpsc411-pub.git?path=cpsc411-lib#2020w2 |
          https://github.com/cpsc411/compilers2.0.git?path=cpsc411-priv/cpsc411-reference-tests#main |
          https://github.com/cpsc411/compilers2.0.git?path=cpsc411-priv/cpsc411-reference-lib#main
    - name: Checkout
      uses: actions/checkout@v2
    - name: Build lib
      run: |
        raco pkg install --batch --auto ./cpsc411-interrogator-lib
    - name: Test lib
      run: |
        raco test -p cpsc411-interrogator-lib
        raco setup --only --pkgs cpsc411-interrogator-lib
